services:
  - type: web
    name: streamer
    runtime: node
    repo: https://github.com/Zeptosec/Streamer.git
    region: oregon
    plan: free
    branch: master
    healthCheckPath: /
    startCommand: npm install && npm start