services:
  type: web
  name: streamer
  runtime: docker
  repo: https://github.com/Zeptosec/Streamer.git
  region: oregon
  plan: free
  branch: master
  rootDir: /
  dockerCommand: npm start
  healthCheckPath: /